[package]
name = "oculars-forks"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chains.workspace = true
eips.workspace = true

[lints]
workspace = true
